### PROGRAMS ###
$terminal = footclient
$menu = wofi --show drun
$browser = setsid brave

bind = $mainMod, P, exec, $menu

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bindd = $mainMod, W, Toggle waybar, exec, pkill -SIGUSR1 waybar
bindd = $mainMod, B, Browser, exec, $browser

