fork = true
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
tabs = true
title-hidden = false
vsync = true

[font]
normal = ["IosevkaTerm Nerd Font"] # Will use the bundled Fira Code Nerd Font by default
size = 16.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4]  # Thin and thick values respectively, for all sizes
